### PR TITLE
Removing insights-client command from compliance playbook temporarily

### PR DESCRIPTION
**Pull request by Jason-RH**

### CODE REVIEW

**Comment by sthirugn** [comment]
To give more context for this change, right now, `insights-client --compliance` will give an error if the system is not associated to any compliance policy in cloud.redhat.com.

**Review by sthirugn — APPROVED** [review]
To give more context for this change, right now, `insights-client --compliance` will give an error if the system is not associated with any compliance policy in cloud.redhat.com.

**Comment by jharting** [comment]
@aleccohan was the template signature created before or after this change?

**Comment by aleccohan** [comment]
@jharting after!  I resigned the template after this was merged

**Comment by jharting** [comment]
@aleccohan awesome! fwiw it would be great to think about some PR hook or similar automation that would tell us in case a change is made that voids the signature (i.e. tell us that some templates need to be resigned). Could be useful both here and in remediations.

**Comment by aleccohan** [comment]
@jharting That's a great idea!  I'll go ahead and make a note about that for next sprint!

**Pull request merged**
