### PR TITLE
fix: Dedent "when" block

### PR DESCRIPTION
**Pull request by Ichimonji10**
The `when` block is a property of the task being invoked, and is not an argument to the `ansible.builtin.package` module.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Verified on a RHEL 8.7 VM with:

```bash
export ANSIBLE_COLLECTIONS_PATHS='/usr/share/rhc-worker-playbook/ansible/collections/ansible_collections/'
ansible-playbook -i localhost, --connection=local pb.yml
```

**Comment by subpop** [comment]
@rexwhite pretty please can you sign the playbook again? :pleading_face:

**Comment by rexwhite** [comment]
@subpop Sure thing!  I'll sign it as soon as I get back from lunch. 🙂

**Review by subpop — CHANGES_REQUESTED** [review]
The commit needs to follow conventionalcommits.org format. Something like:

```
fix: correct indentation of "when" block

The `when` block is a property of the task being invoked, and is not an
argument to the `ansible.builtin.package` module.
```

**Comment by elyezer** [comment]
Sorry to miss that and thank you for taking care of the fix

**Comment by elyezer** [comment]
Thank you @Ichimonji10 , @subpop and @rexwhite for getting this in. I apologize for missing that on the other PR. I will update here once I am able to test it.

**Pull request merged**
