### PR TITLE
perf: Make `insights_setup.yml` more efficient

### PR DESCRIPTION
**Pull request by jeremy-audet**
Install all desired packages in a single package manager transaction. This is more efficient than installing each desired package in a separate package manager transaction.

Fix: https://issues.redhat.com/browse/ESSNTL-3625

### CODE REVIEW

**Comment by Ichimonji10** [comment]
I have no idea if the signatures in `insights_setup.yml` need to be updated or not.

Tested on a RHEL 8.6 VM with:

```bash
export ANSIBLE_COLLECTIONS_PATHS='/usr/share/rhc-worker-playbook/ansible/collections/ansible_collections/'

# current playbook
time ansible-playbook insights_setup.yml -i localhost, --connection=local

# playbook in this pr
time ansible-playbook insights_setup_reduced.yml -i localhost, --connection=local
```

Execution time dropped by ~7 seconds on my VM, from ~31 to ~24 seconds.

**Comment by subpop** [comment]
Any change the the playbook contents require it to be re-signed.

**Comment by subpop** [comment]
This looks good to me, assuming we get the playbook snippets resigned.

**Comment by Ichimonji10** [comment]
I've added a second commit which conditionally registers insights-client. It resolves [ESSNTL-3626](https://issues.redhat.com/browse/ESSNTL-3626). Sample results:

```console
[root@jaudet-rhel86 ~]# insights-client --unregister
Successfully unregistered from the Red Hat Insights Service
[root@jaudet-rhel86 ~]# time ansible-playbook 03_insights_setup.yml -i localhost, --connection=local

PLAY [Insights Setup] ****************************************************************************************

TASK [Gathering Facts] ***************************************************************************************
ok: [localhost]

TASK [Install latest insights-client, rhc, rhc-worker-playbook] **********************************************
ok: [localhost]

TASK [Discover whether insights-client is registered] ********************************************************
ok: [localhost]

TASK [Register insights-client] ******************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


real    0m26.711s
user    0m17.002s
sys     0m3.625s
[root@jaudet-rhel86 ~]# time ansible-playbook 03_insights_setup.yml -i localhost, --connection=local

PLAY [Insights Setup] ****************************************************************************************

TASK [Gathering Facts] ***************************************************************************************
ok: [localhost]

TASK [Install latest insights-client, rhc, rhc-worker-playbook] **********************************************
ok: [localhost]

TASK [Discover whether insights-client is registered] ********************************************************
ok: [localhost]

TASK [Register insights-client] ******************************************************************************
skipping: [localhost]

PLAY RECAP ***************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   


real    0m7.334s
user    0m6.286s
sys     0m0.518s
```

**Comment by rexwhite** [comment]
I can sign this playbook for you if you want.  It'd be easiest if Jeremy grants me write permission to the branch in his repo so I can just push a new signed version of the playbook there...

Just let me know!

**Comment by Ichimonji10** [comment]
The final commit message needs to be amended to comply with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). Prepending `fix: ` to the summary will do the job.

**Pull request merged**
