### PR TITLE
fix: check if dnf or yum are available before installing openscap

### PR DESCRIPTION
**Pull request by elyezer**
Check if either dnf or yum are found in the system and use the package manager found to install openscap.

Fixes ESSNTL-4097

### CODE REVIEW

**Comment by Ichimonji10** [comment]
I like this. It's package-manager agnostic, and it efficiently detects whether the host is using OSTree.

**Comment by rexwhite** [comment]
@subpop If I have permissions to contribute to this PR I can just do it here.  I'll try it and see what happens...

**Comment by elyezer** [comment]
Thank you @rexwhite for the signature.

**Comment by subpop** [comment]
@elyezer when this merges to master, it will autodeploy into stage. Do you have some test machines on hand to verify that the playbook executes correctly?

**Comment by elyezer** [comment]
@subpop I do have, but only RHEL for Edge currently.

**Comment by subpop** [comment]
Yes. That's what I'd like to verify. I know we have QE tests that run mutable hosts already, but for this change, I'd like to get verification from both mutable and immutable tests.

**Comment by elyezer** [comment]
Sure thing and it makes sense. I am waiting for it to get  deployed then so I can try. If there is a way to test before merging please let me know and I can try to provide feedback that way.

**Comment by subpop** [comment]
@elyezer stage is updated with this patch now.

**Comment by elyezer** [comment]
Awesome, I will try to test it ASAP and report back here. Thank you

**Comment by Ichimonji10** [comment]
See #125.

**Pull request merged**
