### PR TITLE
Enable eph env testing in PRs

### PR DESCRIPTION
**Pull request by Ichimonji10**

### CODE REVIEW

**Comment by Ichimonji10** [comment]
I don't know how to make eph env tests run for this PR. :angry:

**Comment by Ichimonji10** [comment]
I've submitted a corresponding MR to the app-interface repository.

**Comment by Ichimonji10** [comment]
This MR is ready to be merged.

**Comment by dehort** [comment]
@Jason-RH I hope its ok that I merged this.  :)

**Comment by Ichimonji10** [comment]
If this causes problems, you can blame it on me. I'm confident in this change.

**Pull request merged**
